name: Build Nightly binary and class documentation

on:
  push:
    branches-ignore: 
      - main

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: make
      run: make BUILD_MODE=Release -j
    
    - name: Build Documentation
      run: make docs

    - name: Push Nightly
      run: sudo /home/deploy/deploy.bash bin/fish "downloads/fish/nightly/${GITHUB_REF##*/}"

    - name: Deploy Docs
      run: cd bin/docs/html && ls -lah && sudo /home/deploy/deploy.bash . docs/fish-dev
