on:
  push:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: [self-hosted, doralitze-gh-mdmx-action-runner]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: make
      run: make test
