name: Build Release Version

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: make
      run: make BUILD_MODE=Release -j

    - name: generate color mixing data
      run: bin/tools/cmhelpdatagen > bin/color_mixing.json

    - name: publish color mixing data
      run cd bin && sudo /home/deploy/deploy.bash color_mixing.json downloads/fish
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Fish
        path: | 
          bin/fish
          bin/tools/ioboardctrl
